[2025-05-01T12:25:12.303+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T12:25:12.336+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_snowflake.upload_csv_to_snowflake manual__2025-05-01T12:24:52.080844+00:00 [queued]>
[2025-05-01T12:25:12.354+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_snowflake.upload_csv_to_snowflake manual__2025-05-01T12:24:52.080844+00:00 [queued]>
[2025-05-01T12:25:12.355+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-01T12:25:12.389+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_csv_to_snowflake> on 2025-05-01 12:24:52.080844+00:00
[2025-05-01T12:25:12.419+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'csv_to_snowflake', 'upload_csv_to_snowflake', 'manual__2025-05-01T12:24:52.080844+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_snowflake.py', '--cfg-path', '/tmp/tmpoxvc12yi']
[2025-05-01T12:25:12.423+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=138) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T12:25:12.426+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask upload_csv_to_snowflake
[2025-05-01T12:25:12.426+0000] {standard_task_runner.py:72} INFO - Started process 152 to run task
[2025-05-01T12:25:12.640+0000] {task_command.py:467} INFO - Running <TaskInstance: csv_to_snowflake.upload_csv_to_snowflake manual__2025-05-01T12:24:52.080844+00:00 [running]> on host 7921725b7597
[2025-05-01T12:25:13.333+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_snowflake' AIRFLOW_CTX_TASK_ID='upload_csv_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T12:24:52.080844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T12:24:52.080844+00:00'
[2025-05-01T12:25:13.336+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-01T12:25:13.604+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-05-01T12:25:13.741+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-05-01T12:25:13.743+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T12:25:13.744+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T12:25:23.542+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/csv_to_snowflake.py:23 UserWarning: The provided table name 'ELECTRI0' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
[2025-05-01T12:25:23.950+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-01T12:25:23.985+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-01T12:25:23.990+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=csv_to_snowflake, task_id=upload_csv_to_snowflake, run_id=manual__2025-05-01T12:24:52.080844+00:00, execution_date=20250501T122452, start_date=20250501T122512, end_date=20250501T122523
[2025-05-01T12:25:24.127+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-01T12:25:24.154+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T12:25:24.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
