[2025-04-30T23:55:01.231+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T23:55:01.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_snowflake_connection.test_snowflake_connection manual__2025-04-30T23:54:39.234799+00:00 [queued]>
[2025-04-30T23:55:01.272+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_snowflake_connection.test_snowflake_connection manual__2025-04-30T23:54:39.234799+00:00 [queued]>
[2025-04-30T23:55:01.276+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-30T23:55:01.299+0000] {taskinstance.py:2890} INFO - Executing <Task(SnowflakeCheckOperator): test_snowflake_connection> on 2025-04-30 23:54:39.234799+00:00
[2025-04-30T23:55:01.318+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_snowflake_connection', 'test_snowflake_connection', 'manual__2025-04-30T23:54:39.234799+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpqopbuhyn']
[2025-04-30T23:55:01.321+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=31) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-30T23:55:01.323+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask test_snowflake_connection
[2025-04-30T23:55:01.325+0000] {standard_task_runner.py:72} INFO - Started process 38 to run task
[2025-04-30T23:55:01.431+0000] {task_command.py:467} INFO - Running <TaskInstance: test_snowflake_connection.test_snowflake_connection manual__2025-04-30T23:54:39.234799+00:00 [running]> on host 6fd6fe70069f
[2025-04-30T23:55:01.877+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_snowflake_connection' AIRFLOW_CTX_TASK_ID='test_snowflake_connection' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T23:54:39.234799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T23:54:39.234799+00:00'
[2025-04-30T23:55:01.883+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-30T23:55:02.159+0000] {sql.py:815} INFO - Executing SQL check: SELECT 1;
[2025-04-30T23:55:02.179+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-04-30T23:55:02.665+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-04-30T23:55:02.668+0000] {connection.py:424} INFO - Snowflake Connector for Python Version: 3.13.2, Python Version: 3.12.9, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-04-30T23:55:02.675+0000] {connection.py:1213} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-30T23:55:02.677+0000] {connection.py:1295} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-30T23:55:05.308+0000] {sql.py:511} INFO - Running statement: SELECT 1;, parameters: None
[2025-04-30T23:55:05.395+0000] {sql.py:520} INFO - Rows affected: 1
[2025-04-30T23:55:05.404+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:468 DeprecationWarning: Import of fetch_one_handler from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-04-30T23:55:05.417+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:469 DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-04-30T23:55:05.420+0000] {snowflake.py:477} INFO - Rows affected: 1
[2025-04-30T23:55:05.421+0000] {snowflake.py:478} INFO - Snowflake query id: 01bc0b9b-0001-554c-0000-000132de409d
[2025-04-30T23:55:05.506+0000] {connection.py:803} INFO - closed
[2025-04-30T23:55:05.564+0000] {connection.py:809} INFO - No async queries seem to be running, deleting session
[2025-04-30T23:55:05.630+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/snowflake/hooks/snowflake.py:487 DeprecationWarning: Import of return_single_query_results from the '***.providers.common.sql.hooks' module is deprecated and will
be removed in the future. Please import it from '***.providers.common.sql.hooks.handlers'.
[2025-04-30T23:55:05.632+0000] {sql.py:818} INFO - Record: (1,)
[2025-04-30T23:55:05.633+0000] {sql.py:826} INFO - Success.
[2025-04-30T23:55:05.650+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-30T23:55:05.651+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=test_snowflake_connection, task_id=test_snowflake_connection, run_id=manual__2025-04-30T23:54:39.234799+00:00, execution_date=20250430T235439, start_date=20250430T235501, end_date=20250430T235505
[2025-04-30T23:55:05.716+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-30T23:55:05.744+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-30T23:55:05.747+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
